### ISSUE TITLE
Wanted features for version 1.0

### ISSUE THREAD

**Issue by DarkDrek** [milesgranger/proffer#17]
What features need to be implemented for the release of 1.0?

**Comment by milesgranger** [comment]
I was thinking about this yesterday. Maybe we're pretty close to making a 1.0. How do you feel about the general API? I thought maybe before that we might address the need to do `.to_owned()` ?

Or maybe that's ok? Otherwise the next best thing would be to implement `Deref` to allow us to more concisely do the same thing? 

What do you think about it?

**Comment by DarkDrek** [comment]
I have some things on my mind we could do
- Using "impl trait" instead of generics for things we want to take as ToString
- Apply the "..Self::Default()" to all construction functions
- Maybe add first class support for the various forms of attributes syntaxes instead of taking them as plain text
- Unify the ability to add things (attributes, documentation, ...) in bulks and one at the time. Maybe per Trait?
- Is formatting the output possible? Including rustfmt (behind a feature flag)?
- Maybe via a own trait we could accept String's and structs at input in some cases like attributes to allow building these things incrementally and adding a already prepared piece of source code

**Comment by milesgranger** [comment]
Lots a good ideas here, I think all are reasonable for 1.0, although I'd say formatting the output is a great idea, but not essential to 1.0, no? 

Let's make a milestone for 1.0 with these as individual issues and take it from there. I've sent you an invite to be a collaborator if you'd like. Also, later tonight I can setup the milestone and issues as well.

**Comment by DarkDrek** [comment]
Thanks for the invite 😃 
Can I assume that a non-goal of this project is to guarantee that the generated source code is valid Rust code?
How much coverage of rust syntax should we strife for?

**Comment by milesgranger** [comment]
You're correct, it was a 'non-goal', so far as the user is perfectly able to input configurations which aren't valid, as obvious as that statement may be.

However, I think that the mechanics of the lib _should_ itself be capable and checked for its logic for creating valid rust code, and you're absolutely right, some form or another should check this claim. (Right now, we just eye ball it)

So maybe with formatting, we get this, is that correct? 
Do you know of a way we can validate in our tests that the generated code is valid? If so, then I retract my previous statement that formatting shouldn't be part of 1.0, if it's attainable without a lot of work, I think that would be perfect to have. Perhaps a function to augment `norm_whitespace` to also validate the syntax of the generated code.

> How much coverage of rust syntax should we strife for?
For me, I think we are _good enough_ in syntax coverage for 1.0, where additional supplements would be minor bumps.

**Comment by DarkDrek** [comment]
Instead of formatting we could include https://github.com/dtolnay/syn or something like that to parse and validate code. As far as I know is syn a relative big (compile-time, binary-size) crate so we have to keep an eye on this. But for tests it should be ok.

**Comment by milesgranger** [comment]
Cool, I haven't used it, but will check it out.

In general, I'd be ok, and even in favor of including something like this in our dev deps to verify the logic of the lib is capable of generating valid rust code (when used correctly).

I'm just not that interested (right now) in incrementally validating that what a user is inputting with the lib will necessarily generate valid code. Maybe something for a 2.0, or as you say, behind a feature is even better.

But alas for now, if we agree, including some validation that our _tests_ generate valid code seems like a sensible requirement for 1.0

**Comment by DarkDrek** [comment]
> But alas for now, if we agree, including some validation that our tests generate valid code seems like a sensible requirement for 1.0
I think this would be great to have and feasible for the 1.0 release.

**Comment by milesgranger** [comment]
Added the issues and milestone, feel free to reword them if you see fit.
I've got free time here and there until after Nov. 14th, then I should have slightly more time to help get this to 1.0. :watch:
